### ISSUE TITLE
Creating the Milestone Report

### ISSUE THREAD

**Issue by ahmetnecipg** [bounswe/2021SpringGroup2#32]
Make sure everything below is ready to be delivered. Check means It's ready and is added to the Milestone Report.

- [x] Communication Plan
- [x] Requirements
- [x] Scenarios and Mockups
- [x] Software Design Documents in UML (Diagrams)
- [x] Project Plan and RAM
- [x] Updating wiki pages with all relevant information

**Comment by berkaydoner** [comment]
I added RAM to the milestone report. Its details are [here](https://github.com/bounswe/2021SpringGroup2/issues/37).

**Comment by ahmetnecipg** [comment]
I added the communication plan to the milestone report. I also added the scenario #2 to the report.
